substitutions:
# Display state on initial start
# Note that the screensaver only starts after the first touch of the display
# Change to ALWAYS_OFF if want the screen to be off after booting, ALWAYS_ON if want it on at start eg for initial troubleshooting
  screenstart: ALWAYS_ON
  # screenstart: ALWAYS_OFF
# Timeout for the screen
  screensaver: 1 min


esphome:
  name: waveshare-21
  friendly_name: Waveshare 2.1
  compile_process_limit: 1

 

# Enable Home Assistant API
api:
  encryption:
    key: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

ota:
  - platform: esphome
    password: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Waveshare-21-Inch"
    password: "U0kYDtDIGtPF"

logger:
  level: DEBUG #makes uart stream available in esphome logstream
  logs:
    component: ERROR
  #Turn off UART logging over RX/TX 
  baud_rate: 0  



esp32:
  board: esp32-s3-devkitc-1
  flash_size: 8MB
  variant: esp32s3
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHFREQ: "80MHz" # this is needed for flashing
      CONFIG_ESPTOOLPY_FLASHMODE_QIO: y
      CONFIG_FLASHMODE_QIO: y
      CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ_240: y
      CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ: '240'
      CONFIG_SPIRAM_RODATA: "y"

psram:
  mode: octal
  speed: 80MHz

preferences:
  flash_write_interval: 5min

# PCA9554 GPIO extender
pca9554:
  - id: p_c_a
    address: 0x20
    i2c_id: bus_a

# Backlight PWM output and light component
output:
    # Backlight LED
  - platform: ledc
    id: gpio_backlight_pwm
    pin: GPIO06
    frequency: 2000Hz
    channel: 0

light:
  - platform: monochromatic
    output: gpio_backlight_pwm
    name: Display Backlight
    icon: mdi:lightbulb-on
    id: display_backlight
    restore_mode: $screenstart
    gamma_correct: 1

#-------------------------------------------
# Touchscreen GT911 i2c
#-------------------------------------------
i2c:
  - id: bus_a
    sda: GPIO15
    scl: GPIO7
    scan: true


# CST820 Touchscreen Controller
touchscreen:
  - platform: cst816
    id: my_touchscreen
    i2c_id: bus_a
    reset_pin:
      pca9554: p_c_a
      number: 1
      mode:
        output: true
      inverted: false
    interrupt_pin: GPIO16
    skip_probe: true
    on_update:
        - lvgl.label.update:
            id: coord_text
            text: !lambda return str_sprintf("Touch points:\n id=%d x=%d, y=%d", touches[0].id, touches[0].x, touches[0].y);
        - lambda: |-
            for (auto touch: touches)  {
                if (touch.state <= 2) {
                  ESP_LOGI("Touch points:", "id=%d x=%d, y=%d", touch.id, touch.x, touch.y);
                }
            }
    on_release:
        - script.execute: screentime


#-------------------------------------------
# Display ST7701S spi
#-------------------------------------------
spi:
  - id: spi_lcd
    clk_pin: GPIO02
    mosi_pin: GPIO01
    interface: spi3

display:
  - platform: st7701s
    id: my_display
    spi_id: spi_lcd
    spi_mode: MODE1
    color_order: rgb
    auto_clear_enabled: false
    dimensions:
      width: 480
      height: 480
    cs_pin:
      pca9554: p_c_a
      number: 2
    reset_pin:
      pca9554: p_c_a
      number: 0
    de_pin: GPIO40
    hsync_pin: GPIO38
    vsync_pin: GPIO39
    pclk_pin: GPIO41
    init_sequence:
      - delay 120ms
      - [ 0xFF, 0x77, 0x01, 0x00, 0x00, 0x10 ]
      - [ 0xC0, 0x3B, 0x00 ]
      - [ 0xC1, 0x0B, 0x02 ]
      - [ 0xC2, 0x07, 0x02 ]
      - [ 0xCC, 0x10 ]
      - [ 0xCD, 0x08 ]
      - [ 0xB0, 0x00, 0x11, 0x16, 0x0E, 0x11, 0x06, 0x05, 0x09, 0x08, 0x21, 0x06, 0x13, 0x10, 0x29, 0x31, 0x18 ]
      - [ 0xB1, 0x00, 0x11, 0x16, 0x0E, 0x11, 0x07, 0x05, 0x09, 0x09, 0x21, 0x05, 0x13, 0x11, 0x2A, 0x31, 0x18 ]
      - [ 0xFF, 0x77, 0x01, 0x00, 0x00, 0x11 ]
      - [ 0xB0, 0x6D ]
      - [ 0xB1, 0x37 ]
      - [ 0xB2, 0x81 ]
      - [ 0xB3, 0x80 ]
      - [ 0xB5, 0x43 ]
      - [ 0xB7, 0x85 ]
      - [ 0xB8, 0x20 ]
      - [ 0xC1, 0x78 ]
      - [ 0xC2, 0x78 ]
      - [ 0xD0, 0x88 ]
      - [ 0xE0, 0x00, 0x00, 0x02 ]
      - [ 0xE1, 0x03, 0xA0, 0x00, 0x00, 0x00, 0x04, 0xA0, 0x00, 0x00, 0x20, 0x20 ]
      - [ 0xE2, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 ]
      - [ 0xE3, 0x00, 0x00, 0x11, 0x00 ]
      - [ 0xE4, 0x22, 0x00 ]
      - [ 0xE5, 0x05, 0xEC, 0xA0, 0xA0, 0x07, 0xEE, 0xA0, 0xA0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 ]
      - [ 0xE6, 0x00, 0x00, 0x11, 0x00 ]
      - [ 0xE7, 0x22, 0x00 ]
      - [ 0xE8, 0x06, 0xED, 0xA0, 0xA0, 0x08, 0xEF, 0xA0, 0xA0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 ]
      - [ 0xEB, 0x00, 0x00, 0x40, 0x40, 0x00, 0x00, 0x00 ]
      - [ 0xED, 0xFF, 0xFF, 0xFF, 0xBA, 0x0A, 0xBF, 0x45, 0xFF, 0xFF, 0x54, 0xFB, 0xA0, 0xAB, 0xFF, 0xFF, 0xFF ]
      - [ 0xEF, 0x10, 0x0D, 0x04, 0x08, 0x3F, 0x1F ]
      - [ 0xFF, 0x77, 0x01, 0x00, 0x00, 0x13 ]
      - [ 0x36, 0x00 ]
      - [ 0x3A, 0x66 ]
      - [ 0x11 ]
      - delay 255ms
      - [ 0x20 ]
      - delay 120ms
      - [ 0x29 ]
      - delay 120ms
    data_pins:
      red:
        - 46       #r1
        - 3        #r2
        - 8        #r3
        - 18       #r4
        - 17       #r5
      green:
        - 14       #g0
        - 13       #g1
        - 12       #g2
        - 11       #g3
        - 10       #g4
        - 9        #g5
      blue:
        - 5        #b1
        - 45       #b2
        - 48       #b3
        - 47       #b4
        - 21       #b5

script:
  - id: screentime
    mode: restart
    then:
      - light.turn_on: display_backlight
      - delay: $screensaver
      - light.turn_off: display_backlight



# LVGL Configuration
lvgl:
  - id: lvgl_display
    displays:
      - my_display
    widgets:
      - label:
          id: coord_text
          align: CENTER
          text_align: CENTER
          text_color: red
          text_font: montserrat_28
          text: 'Touch the screen'
    on_idle:
      timeout: !lambda "return (id(display_timeout).state * 1000);"
      then:
        - logger.log: "LVGL is idle"
        - light.turn_off:
            id: display_backlight
        - lvgl.pause:

number:
  - platform: template
    name: LVGL Screen timeout
    optimistic: true
    id: display_timeout
    unit_of_measurement: "s"
    initial_value: 45
    restore_value: true
    min_value: 10
    max_value: 180
    step: 5
    mode: box
    
